"""Sağlık künyesi form şeması — widget bu alanlarla formu çizer."""

FORM_SCHEMA_V1 = {
    "version": "1.1",
    "title": "Kişisel Sağlık Künyesi",
    "description": "Sağlık bilgilerinizi kaydedin. QR kodunuz sabit kalır; lab sonuçlarınız otomatik eklenir.",
    "sections": [
        {
            "id": "emergency",
            "title": "Acil Sağlık Özeti",
            "fields": [
                {"key": "full_name", "label": "Ad Soyad", "type": "text", "required": True},
                {"key": "birth_date", "label": "Doğum Tarihi", "type": "date"},
                {"key": "age", "label": "Yaş", "type": "number"},
                {
                    "key": "sex",
                    "label": "Cinsiyet",
                    "type": "select",
                    "options": ["Kadın", "Erkek", "Diğer", "Belirtmek istemiyorum"],
                },
                {
                    "key": "blood_type",
                    "label": "Kan Grubu",
                    "type": "select",
                    "options": ["0 Rh-", "0 Rh+", "A Rh-", "A Rh+", "B Rh-", "B Rh+", "AB Rh-", "AB Rh+", "Bilinmiyor"],
                },
                {"key": "critical_allergies", "label": "Kritik Alerjiler", "type": "textarea"},
                {"key": "active_diagnoses", "label": "Aktif Önemli Tanılar", "type": "textarea"},
                {"key": "critical_medications", "label": "Güncel Kritik İlaçlar", "type": "textarea"},
                {
                    "key": "pregnancy_status",
                    "label": "Gebelik Durumu",
                    "type": "select",
                    "options": ["Uygulanmıyor", "Yok", "Olası", "Doğrulanmış"],
                },
                {"key": "implants_devices", "label": "İmplant / Protez / Cihaz", "type": "textarea"},
                {"key": "communication_support", "label": "İletişim Desteği (dil, işitme, görme vb.)", "type": "text"},
                {"key": "special_notes", "label": "Acil Durumda Bilinmesi Gerekenler", "type": "textarea"},
            ],
        },
        {
            "id": "personal",
            "title": "Kişisel, İletişim ve İdari Bilgiler",
            "fields": [
                {"key": "birth_place", "label": "Doğum Yeri", "type": "text"},
                {"key": "height_cm", "label": "Boy (cm)", "type": "number"},
                {"key": "weight_kg", "label": "Kilo (kg)", "type": "number"},
                {"key": "measurement_date", "label": "Ölçüm Tarihi", "type": "date"},
                {"key": "languages", "label": "Ana Dil / Diğer Diller", "type": "text"},
                {"key": "phone", "label": "Telefon", "type": "text"},
                {"key": "email", "label": "E-posta", "type": "email"},
                {"key": "address", "label": "Adres", "type": "textarea"},
                {"key": "social_security", "label": "Sosyal Güvenlik", "type": "text"},
                {"key": "private_insurance", "label": "Özel Sağlık Sigortası", "type": "text"},
                {"key": "family_doctor", "label": "Aile Hekimi / Pediatrist", "type": "text"},
                {"key": "preferred_hospital", "label": "Tercih Edilen Kurum", "type": "text"},
            ],
        },
        {
            "id": "emergency_contacts",
            "title": "Acil Durum ve Yetkili İletişim Kişileri",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "Ad Soyad", "type": "text"},
                {"key": "relation", "label": "Yakınlık / Rol", "type": "text"},
                {"key": "phone", "label": "Telefon", "type": "text"},
                {"key": "email", "label": "E-posta", "type": "text"},
                {"key": "notes", "label": "Yetki / Not", "type": "text"},
            ],
        },
        {
            "id": "accessibility",
            "title": "İletişim, Erişilebilirlik ve Karar Desteği",
            "fields": [
                {
                    "key": "communication_preference",
                    "label": "İletişim tercihi",
                    "type": "select",
                    "options": ["Sözlü", "Yazılı", "İşaret dili", "Tercüman", "Diğer"],
                },
                {"key": "accessibility_needs", "label": "Erişilebilirlik ihtiyacı", "type": "textarea"},
                {"key": "legal_representative", "label": "Veli / Vasi / Yasal temsilci", "type": "text"},
                {"key": "decision_support", "label": "Sağlık kararlarında destek kişisi", "type": "text"},
                {"key": "privacy_preference", "label": "Mahremiyet / paylaşım tercihi", "type": "textarea"},
            ],
        },
        {
            "id": "allergies",
            "title": "Alerjiler, Duyarlılıklar ve İstenmeyen Reaksiyonlar",
            "type": "list",
            "item_fields": [
                {"key": "allergen", "label": "Alerjen", "type": "text"},
                {
                    "key": "type",
                    "label": "Tür",
                    "type": "select",
                    "options": ["İlaç", "Gıda", "Çevresel", "Lateks", "Kontrast madde", "Diğer"],
                },
                {"key": "reaction", "label": "Reaksiyon", "type": "text"},
                {
                    "key": "severity",
                    "label": "Şiddet",
                    "type": "select",
                    "options": ["Hafif", "Orta", "Şiddetli", "Anafilaksi"],
                },
                {"key": "first_last", "label": "İlk / Son tarih", "type": "text"},
                {"key": "plan", "label": "Acil Plan", "type": "text"},
            ],
        },
        {
            "id": "drug_intolerances",
            "title": "İlaç Yan Etkileri ve İntoleranslar",
            "type": "list",
            "item_fields": [
                {"key": "drug", "label": "İlaç / Etken", "type": "text"},
                {"key": "effect", "label": "Yan Etki / İntolerans", "type": "text"},
                {"key": "date", "label": "Tarih", "type": "text"},
                {"key": "alternative", "label": "Sonuç / Alternatif", "type": "text"},
            ],
        },
        {
            "id": "diagnoses",
            "title": "Aktif Sağlık Sorunları ve Tanılar",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "Tanı / Sorun", "type": "text"},
                {"key": "started_at", "label": "Başlangıç", "type": "text"},
                {
                    "key": "status",
                    "label": "Durum",
                    "type": "select",
                    "options": ["Aktif", "Kontrol altında", "İyileşme", "Takipte"],
                },
                {"key": "doctor", "label": "Takip Eden", "type": "text"},
                {"key": "treatment", "label": "Tedavi", "type": "text"},
                {"key": "next_plan", "label": "Sonraki Plan", "type": "text"},
            ],
        },
        {
            "id": "past_conditions",
            "title": "Çözülen / Geçmiş Hastalıklar",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "Hastalık / Olay", "type": "text"},
                {"key": "period", "label": "Dönem", "type": "text"},
                {"key": "outcome", "label": "Tedavi / Sonuç", "type": "text"},
                {"key": "residual", "label": "Kalıcı Etki / Risk", "type": "text"},
            ],
        },
        {
            "id": "surgeries",
            "title": "Ameliyatlar ve Tıbbi Girişimler",
            "type": "list",
            "item_fields": [
                {"key": "date", "label": "Tarih", "type": "text"},
                {"key": "procedure", "label": "İşlem / Bölge", "type": "text"},
                {"key": "reason", "label": "Neden", "type": "text"},
                {"key": "hospital", "label": "Hastane / Hekim", "type": "text"},
                {"key": "complications", "label": "Komplikasyon", "type": "text"},
            ],
        },
        {
            "id": "hospitalizations",
            "title": "Hastane Yatışları ve Acil Başvurular",
            "type": "list",
            "item_fields": [
                {"key": "dates", "label": "Giriş – Çıkış", "type": "text"},
                {"key": "reason", "label": "Neden", "type": "text"},
                {"key": "diagnosis", "label": "Tanı", "type": "text"},
                {"key": "treatment", "label": "Tedavi / İşlem", "type": "text"},
                {"key": "outcome", "label": "Sonuç / Takip", "type": "text"},
            ],
        },
        {
            "id": "medications",
            "title": "Güncel İlaçlar",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "İlaç / Etken", "type": "text"},
                {"key": "dose", "label": "Doz / Form", "type": "text"},
                {"key": "frequency", "label": "Sıklık / Yol", "type": "text"},
                {"key": "reason", "label": "Neden", "type": "text"},
                {"key": "started_at", "label": "Başlama", "type": "text"},
                {"key": "prescriber", "label": "Reçete Eden", "type": "text"},
            ],
        },
        {
            "id": "supplements",
            "title": "Vitamin, Mineral ve Supplementler",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "Ürün", "type": "text"},
                {"key": "dose", "label": "Doz / Form", "type": "text"},
                {"key": "frequency", "label": "Sıklık", "type": "text"},
                {"key": "purpose", "label": "Amaç", "type": "text"},
                {"key": "started_at", "label": "Başlama", "type": "text"},
            ],
        },
        {
            "id": "vaccinations",
            "title": "Aşılar ve Bağışıklık",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "Aşı", "type": "text"},
                {"key": "date", "label": "Tarih", "type": "text"},
                {"key": "dose", "label": "Doz / Seri", "type": "text"},
                {"key": "next_due", "label": "Sonraki", "type": "text"},
                {"key": "reaction", "label": "Reaksiyon", "type": "text"},
            ],
        },
        {
            "id": "family_history",
            "title": "Aile Sağlık Geçmişi",
            "type": "list",
            "item_fields": [
                {"key": "relation", "label": "Yakınlık", "type": "text"},
                {"key": "condition", "label": "Hastalık / Durum", "type": "text"},
                {"key": "age_at_diagnosis", "label": "Tanı Yaşı", "type": "text"},
                {"key": "notes", "label": "Not", "type": "text"},
            ],
        },
        {
            "id": "lifestyle",
            "title": "Yaşam Tarzı, Sosyal ve Çevresel Bilgiler",
            "fields": [
                {"key": "diet", "label": "Beslenme düzeni", "type": "textarea"},
                {"key": "activity", "label": "Fiziksel aktivite", "type": "textarea"},
                {"key": "sleep", "label": "Uyku", "type": "textarea"},
                {"key": "smoking", "label": "Tütün / nikotin", "type": "text"},
                {"key": "alcohol", "label": "Alkol / madde", "type": "text"},
                {"key": "occupation", "label": "Meslek / okul", "type": "text"},
                {"key": "environmental_risks", "label": "Mesleki / çevresel riskler", "type": "textarea"},
                {"key": "living_conditions", "label": "Ev ve yaşam koşulları", "type": "textarea"},
            ],
        },
        {
            "id": "devices",
            "title": "Protez, İmplant ve Tıbbi Cihazlar",
            "type": "list",
            "item_fields": [
                {"key": "device", "label": "Cihaz / İmplant", "type": "text"},
                {"key": "location", "label": "Yer / Taraf", "type": "text"},
                {"key": "model", "label": "Marka / Model", "type": "text"},
                {"key": "date", "label": "Takılma tarihi", "type": "text"},
                {"key": "mri_safe", "label": "MR uyumu", "type": "text"},
            ],
        },
        {
            "id": "womens_health",
            "title": "Kadın Sağlığı (uygulanıyorsa)",
            "fields": [
                {"key": "last_period", "label": "Son adet tarihi / düzen", "type": "text"},
                {"key": "gynecologic_diagnoses", "label": "Jinekolojik tanılar", "type": "textarea"},
                {"key": "contraception", "label": "Doğum kontrolü / hormon", "type": "text"},
                {"key": "last_exam", "label": "Son jinekolojik muayene", "type": "text"},
                {"key": "cervix_screening", "label": "Serviks taraması", "type": "text"},
                {"key": "breast_screening", "label": "Meme sağlığı / tarama", "type": "text"},
            ],
        },
        {
            "id": "mens_health",
            "title": "Erkek Sağlığı (uygulanıyorsa)",
            "fields": [
                {"key": "urologic_issues", "label": "Ürolojik tanılar / şikâyetler", "type": "textarea"},
                {"key": "prostate", "label": "Prostat değerlendirmesi", "type": "text"},
                {"key": "hormone_therapy", "label": "Hormon tedavisi", "type": "text"},
            ],
        },
        {
            "id": "doctors",
            "title": "Takip Eden Hekimler ve Kuruluşlar",
            "type": "list",
            "item_fields": [
                {"key": "name", "label": "Hekim / Kurum", "type": "text"},
                {"key": "specialty", "label": "Branş / Rol", "type": "text"},
                {"key": "phone", "label": "Telefon / E-posta", "type": "text"},
                {"key": "last_visit", "label": "Son Görüşme", "type": "text"},
                {"key": "next_appointment", "label": "Sonraki Randevu", "type": "text"},
            ],
        },
        {
            "id": "directives",
            "title": "Özel Tercihler ve Hukuki Durumlar",
            "fields": [
                {"key": "organ_donation", "label": "Organ / doku bağışı", "type": "text"},
                {"key": "advance_directive", "label": "İleri sağlık direktifi", "type": "text"},
                {"key": "health_proxy", "label": "Sağlık vekili / temsilci", "type": "text"},
                {"key": "blood_product_preference", "label": "Kan ürünü tercihi / kısıtı", "type": "text"},
                {"key": "cultural_needs", "label": "Dini / kültürel ihtiyaç", "type": "textarea"},
            ],
        },
        {
            "id": "notes",
            "title": "Ek Notlar",
            "fields": [
                {"key": "extra_notes", "label": "Özel durumlar / ek açıklama", "type": "textarea"},
            ],
        },
    ],
}
